
title: Weiho's Blog - Life's a stuggle,try everything
email: h4x0er@secbug.org
description: 关注企业安全、WEB安全、企业安全架构、Linux Hacking、网站漏洞、互联网安全知识、渗透测试、安全培训
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.weiho.xyz" # the base hostname & protocol for your site
#twitter_username:
github_username:  zhaoweiho

# Build settings
markdown: kramdown
paginate: 3
gems: [jekyll-paginate]
paginate_path: "/page/:num"
